version: '2'

volumes:
    mantisbugtracker:
        driver: local

services:
###########################
# Setup the mantis container
###########################
  mantisbt:
    build: ./
    ports:
      - "8989:80"
    links:
      - mysql
    restart: always

###########################
# Setup the mysql container
###########################
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantis
      - MYSQL_PASSWORD=mantis
    restart: always

###########################
# Setup the postgres container
###########################  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    restart: always
